version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    command: npm start
    restart: always
    ports:
      - "8080:3000"
